#project
project: AQ
name: mnist
## general args
# model
arch : resnet9
n_dw_emb : 128
n_pw_emb : 128
n_f_emb : 128
out_planes: 32
beta : 0.5
gs : 1

# train
lr : 0.001
epoch : 60
num_workers : 4
batch_size : 128
optimizer : adam
distributed : 0
gpus : 1
use_amp : 1
# data
dataset : mnist




